2023-06-03

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,71 +1,79 @@
 #!/usr/bin/env bash
 # github: https://github.com/xvoland/Extract/blob/master/extract.sh
 
+help () {
+	cat << EOF
+usage: $(basename $0) [filename]
+note:
+	Everything after the first '.' in [filename]
+	is condidered to be the extension.
+EOF
+}
+
 [ $# -eq 0 ] && {
-	echo "usage: $(basename $0) [filenames]" >&2
+	help >&2
 	exit 1
 }
 
-for n in "$@"; do
-	[ ! -f "$n" ] && {
-		echo "$(basename $0): error: '$n' - file doesn't exist" >&2
+[ ! -f "$1" ] && {
+	echo "$(basename $0): error: '$1' - file doesn't exist" >&2
+	exit 1
+}
+
+case ${1#*.} in
+	cbt|tar.bz2|tar.gz|tar.xz|tbz2|tgz|txz|tar)
+		tar xvf -p "$1" 
+		;;
+	lzma)
+		unlzma ./"$1" 
+		;;
+	bz2)
+		bunzip2 ./"$1" 
+		;;
+	cbr|rar)
+		unrar x -ad ./"$1" 
+		;;
+	gz)
+		gunzip ./"$1" 
+		;;
+	cbz|epub|zip)
+		unzip ./"$1" 
+		;;
+	z)
+		uncompress ./"$1" 
+		;;
+	7z|apk|arj|cab|cb7|chm|deb|iso|lzh|msi|pkg|rpm|udf|wim|xar|vhd)
+		7z x ./"$1" 
+		;;
+	xz)
+		unxz ./"$1" 
+		;;
+	exe)
+		cabextract ./"$1" 
+		;;
+	cpio)
+		cpio -id < ./"$1" 
+		;;
+	cba|ace)
+		unace x ./"$1" 
+		;;
+	zpaq)
+		zpaq x ./"$1" 
+		;;
+	arc)
+		arc e ./"$1" 
+		;;
+	cso)
+		ciso 0 ./"$1" ./"$1.iso" && extract "$1.iso" && \rm -f "$1" 
+		;;
+	zlib)
+		zlib-flate -uncompress < ./"$1" > ./"$1.tmp" && mv ./"$1.tmp" ./"${n%.*zlib}" && rm -f "$1" 
+		;;
+	dmg)
+		hdiutil mount ./"$1" -mountpoint "./$1.mounted"
+		;;
+	*)
+		echo "$(basename $0): error: '$1' - unknown archive method" >&2
 		exit 1
-	}
-	case "${n#*.}" in
-		cbt|tar.bz2|tar.gz|tar.xz|tbz2|tgz|txz|tar)
-			tar xvf -p "$n" 
-			;;
-		lzma)
-			unlzma ./"$n" 
-			;;
-		bz2)
-			bunzip2 ./"$n" 
-			;;
-		cbr|rar)
-			unrar x -ad ./"$n" 
-			;;
-		gz)
-			gunzip ./"$n" 
-			;;
-		cbz|epub|zip)
-			unzip ./"$n" 
-			;;
-		z)
-			uncompress ./"$n" 
-			;;
-		7z|apk|arj|cab|cb7|chm|deb|iso|lzh|msi|pkg|rpm|udf|wim|xar|vhd)
-			7z x ./"$n" 
-			;;
-		xz)
-			unxz ./"$n" 
-			;;
-		exe)
-			cabextract ./"$n" 
-			;;
-		cpio)
-			cpio -id < ./"$n" 
-			;;
-		cba|ace)
-			unace x ./"$n" 
-			;;
-		zpaq)
-			zpaq x ./"$n" 
-			;;
-		arc)
-			arc e ./"$n" 
-			;;
-		cso)
-			ciso 0 ./"$n" ./"$n.iso" && extract "$n.iso" && \rm -f "$n" 
-			;;
-		zlib)
-			zlib-flate -uncompress < ./"$n" > ./"$n.tmp" && mv ./"$n.tmp" ./"${n%.*zlib}" && rm -f "$n" 
-			;;
-		dmg)
-			hdiutil mount ./"$n" -mountpoint "./$n.mounted"
-			;;
-		*)
-			echo "$(basename $0): error: '$n' - unknown archive method" >&2
-			exit 1
-			;;
-	esac
-done
+		;;
+esac
