monthly

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -2,16 +2,15 @@
 # github: https://github.com/xvoland/Extract/blob/master/extract.sh
 
 [ $# -eq 0 ] && {
-	echo "usage: extract [filenames]"
-	exit 0
+	echo "usage: $(basename $0) [filenames]" >&2
+	exit 1
 }
 
 for n in "$@"; do
 	[ ! -f "$n" ] && {
-		echo "$0: error: '$n' - file doesn't exist" >&2
+		echo "$(basename $0): error: '$n' - file doesn't exist" >&2
 		exit 1
 	}
-
 	case "${n#*.}" in
 		cbt|tar.bz2|tar.gz|tar.xz|tbz2|tgz|txz|tar)
 			tar xvf -p "$n" 
@@ -65,7 +64,7 @@ for n in "$@"; do
 			hdiutil mount ./"$n" -mountpoint "./$n.mounted"
 			;;
 		*)
-			echo "$0: error: '$n' - unknown archive method" >&2
+			echo "$(basename $0): error: '$n' - unknown archive method" >&2
 			exit 1
 			;;
 	esac
diff --git a/bin/latexit b/bin/latexit
--- a/bin/latexit
+++ b/bin/latexit
@@ -1,38 +1,19 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ###############################################################################
 # -*- encoding: UTF-8 -*-                                                     #
 # Description: latexit: fast way of creating LaTeX snippets.                  #
 # Author: Jesse C. Chen  (jessekelighine@gmail.com)                           #
-# Last Modified: 2023-02-16                                                   #
+# Last Modified: 2023-04-06                                                   #
 #                                                                             #
 ###############################################################################
-
-_help () {
-	cat << EOF
-usage: latexit [options] <LATEX_COMMAND>
-options:
-        -a --preamble <LATEX_COMMAND> add command to preamble
-        -d --directory <DIRECTORY>    set output directory (default: ~/Desktop)
-	-e --engine <LATEX_ENGIN>     set LaTeX compilation engine (default: pdflatex)
-        -f --format <FORMAT>          set output file format (default: png)
-                * png       png (default: white background)
-                * png-t     png (transparent background)
-                * svg       svg file
-                * pdf       pdf file
-        -n --name <FILENAME>          set output filename (default: latexit_snippet)
-        -p --package <PACKAGE>        add package to preamble
-png options:
-           --density <NUMBER>         set density of png output (default: 1200)
-           --background <HEX_COLOR>   set background of png otput (default: #FFFFFF)
-EOF
-}
 
 ### Default Packages and Preamble #############################################
 
 PACKAGES=( "amsmath" "mathtools" "amssymb" "mathrsfs" )
 PREAMBLES=()
 POSITIONAL_ARGS=()
+error () { echo "$(basename $0): error: $1" >&2 ; }
 
 while [[ $# -gt 0 ]]; do
 	case $1 in
@@ -69,7 +50,7 @@ while [[ $# -gt 0 ]]; do
 			shift; shift
 			;;
 		-* | --*)
-			echo "unknown option $1" >&2
+			error "unknown option $1."
 			exit 1
 			;;
 		*)
@@ -89,13 +70,35 @@ output="$directory/${filename:-latexit_snippet}"
 
 ### Error Check ###############################################################
 
+message () {
+	cat << EOF
+usage: $(basename $0) [options] <LATEX_COMMAND>
+options:
+        -a --preamble <LATEX_COMMAND> add command to preamble
+        -d --directory <DIRECTORY>    set output directory (default: ~/Desktop)
+	-e --engine <LATEX_ENGIN>     set LaTeX compilation engine (default: pdflatex)
+        -f --format <FORMAT>          set output file format (default: png)
+                * png       png (default: white background)
+                * png-t     png (transparent background)
+                * svg       svg file
+                * pdf       pdf file
+        -n --name <FILENAME>          set output filename (default: latexit_snippet)
+        -p --package <PACKAGE>        add package to preamble
+                * default packages:
+                  ${PACKAGES[@]}
+png options:
+           --density <NUMBER>         set density of png output (default: 1200)
+           --background <HEX_COLOR>   set background of png otput (default: #FFFFFF)
+EOF
+}
+
 [[ $# -ne 1 ]] && {
-	_help >&2
+	message >&2
 	exit 1
 }
 
 [[ -f "$output.${format:0:3}" ]] && {
-	echo "error: file $output.${format:0:3} already exists." >&2
+	error "file $output.${format:0:3} already exists."
 	exit 1
 }
 
@@ -138,7 +141,7 @@ case ${format:-png} in
 		;;
 	*)
 		rm "$output.pdf"
-		echo "unrecognised format" >&2
+		error "unrecognised format."
 		;;
 esac
 
diff --git a/bin/pdfrmp1 b/bin/pdfrmp1
--- a/bin/pdfrmp1
+++ b/bin/pdfrmp1
@@ -1,11 +1,15 @@
 #!/usr/bin/env bash
 
-[[ $# -lt 1 ]] && {
+message () {
 	cat << EOF
-usage: pdfrmp1 [file.pdf]
+usage: $(basename $0) [file.pdf]
 description: remove first page of pdf
 EOF
-	exit 0
+}
+
+[[ $# -lt 1 ]] && {
+	message >&2
+	exit 1
 }
 
 temp=".temp-$(date '+%X-%F').pdf"
@@ -19,5 +23,5 @@ pdfsplit "$1" 2 "$pages" "$temp"
 	exit 0
 }
 
-echo "$0: an error occurred." >&2
+echo "$(basename $0): an error occurred." >&2
 exit 1
